allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  esbuild: false
  msgpackr-extract: true
  unrs-resolver: false
  vue-demi: false
minimumReleaseAgeExclude:
  - '@pinia/nuxt@1.0.0'
  - pinia@4.0.0

publicHoistPattern:
  - '*eslint*'
shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - effect@4.0.0-beta.98
  - '@effect/vitest@4.0.0-beta.98'
  - semver@6.3.1
  - synckit@0.10.4
