allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  esbuild: false
  msgpackr-extract: true
  unrs-resolver: false
  vue-demi: false
minimumReleaseAgeExclude:
  - '@pinia/nuxt@1.0.0'
  - pinia@4.0.0
  - '@ai-sdk/gateway@4.0.62'
  - '@ai-sdk/openai@4.0.46'
  - '@ai-sdk/provider-utils@5.0.29'
  - '@nuxt/ui@4.11.0'
  - ai@7.0.77
  - eslint@10.9.0

publicHoistPattern:
  - '*eslint*'
shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - effect@4.0.0-beta.98
  - '@effect/vitest@4.0.0-beta.98'
  - semver@6.3.1
  - synckit@0.10.4
